### ISSUE TITLE
problem with band plot with wannier90 output using TBLattice methods

### ISSUE THREAD

**Issue by ParthaSarathiRana** [TRIQS/tprf#34]
Hi,
I am trying to plot bands for a multi-orbital tb model from wannier90 output. I am following the methods used to construct a band for square lattice given in the tutorial. But I can't reproduce the original band plot. Can you please help me with the issue?

[wann_tprf.py.txt](https://github.com/TRIQS/tprf/files/9046033/wann_tprf.py.txt)

[tprf-bands](https://user-images.githubusercontent.com/90611888/177319641-d192b828-f436-440f-9242-06153fa896ba.png)

[wannier90-bands](https://user-images.githubusercontent.com/90611888/177319677-57ab3ed5-e951-473e-b4a3-c83636c2a4af.png)

**Comment by HugoStrand** [comment]
Dear Rana,

I am sorry, I am not able to reproduce your results given only the python script and the plots. 

Could you please also share the `wannier90_hr.dat`, `wannier90.wout`, `wannier90-bands.dat` etc. files?

Best, Hugo

**Comment by ParthaSarathiRana** [comment]
I am sharing the wannier90 outputs
[wannier90_hr.dat.txt](https://github.com/TRIQS/tprf/files/9047405/wannier90_hr.dat.txt)
[wannier90.wout.txt](https://github.com/TRIQS/tprf/files/9047410/wannier90.wout.txt)
[wannier90-bands.dat.txt](https://github.com/TRIQS/tprf/files/9047414/wannier90-bands.dat.txt)

**Comment by HugoStrand** [comment]
Dear Rana,

The problem is that the tight binding object in `TPRF` does not give you the eigenvalues of the bands at each k-point. It gives you a matrix whose eigenvalues are the band energies.

Here is a fixed plot script and the resulting figure.

Best, Hugo

[plot.py.txt](https://github.com/TRIQS/tprf/files/9105685/plot.py.txt)


![figure_tprf](https://user-images.githubusercontent.com/1188035/178825141-0bf0b49e-848b-47f0-9f66-d6c4b0f52c2e.png)

**Comment by ParthaSarathiRana** [comment]
Thanks,
I got the point.
